# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Nathan is editing this to generate diffs in lots of files.
#     He won't submit this change.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/container/property/regionalcluster_master_auth_client_certificate_config'
module GoogleInSpec
  module Container
    module Property
      class RegionalClusterMasterAuth
        attr_reader :username

        attr_reader :password

        attr_reader :client_certificate_config

        attr_reader :cluster_ca_certificate

        attr_reader :client_certificate

        attr_reader :client_key

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @username = args['username']
          @password = args['password']
          @client_certificate_config = GoogleInSpec::Container::Property::RegionalClusterMasterAuthClientCertificateConfig.new(args['clientCertificateConfig'], to_s)
          @cluster_ca_certificate = args['clusterCaCertificate']
          @client_certificate = args['clientCertificate']
          @client_key = args['clientKey']
        end

        def to_s
          "#{@parent_identifier} RegionalClusterMasterAuth"
        end
      end
    end
  end
end
