# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/appengine/property/standardappversion_automatic_scaling_cpu_utilization'
require 'google/appengine/property/standardappversion_automatic_scaling_disk_utilization'
require 'google/appengine/property/standardappversion_automatic_scaling_network_utilization'
require 'google/appengine/property/standardappversion_automatic_scaling_request_utilization'
require 'google/appengine/property/standardappversion_automatic_scaling_standard_scheduler_settings'
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionAutomaticScaling
        attr_reader :min_pending_latency

        attr_reader :standard_scheduler_settings

        attr_reader :max_idle_instances

        attr_reader :request_utilization

        attr_reader :min_idle_instances

        attr_reader :max_total_instances

        attr_reader :min_total_instances

        attr_reader :network_utilization

        attr_reader :cool_down_period

        attr_reader :max_concurrent_requests

        attr_reader :max_pending_latency

        attr_reader :cpu_utilization

        attr_reader :disk_utilization

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @min_pending_latency = args['minPendingLatency']
          @standard_scheduler_settings = GoogleInSpec::AppEngine::Property::StandardAppVersionAutomaticScalingStandardSchedulerSettings.new(args['standardSchedulerSettings'], to_s)
          @max_idle_instances = args['maxIdleInstances']
          @request_utilization = GoogleInSpec::AppEngine::Property::StandardAppVersionAutomaticScalingRequestUtilization.new(args['requestUtilization'], to_s)
          @min_idle_instances = args['minIdleInstances']
          @max_total_instances = args['maxTotalInstances']
          @min_total_instances = args['minTotalInstances']
          @network_utilization = GoogleInSpec::AppEngine::Property::StandardAppVersionAutomaticScalingNetworkUtilization.new(args['networkUtilization'], to_s)
          @cool_down_period = args['coolDownPeriod']
          @max_concurrent_requests = args['maxConcurrentRequests']
          @max_pending_latency = args['maxPendingLatency']
          @cpu_utilization = GoogleInSpec::AppEngine::Property::StandardAppVersionAutomaticScalingCpuUtilization.new(args['cpuUtilization'], to_s)
          @disk_utilization = GoogleInSpec::AppEngine::Property::StandardAppVersionAutomaticScalingDiskUtilization.new(args['diskUtilization'], to_s)
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionAutomaticScaling"
        end
      end
    end
  end
end
