# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionAutomaticScalingDiskUtilization
        attr_reader :target_write_bytes_per_second

        attr_reader :target_read_bytes_per_second

        attr_reader :target_read_ops_per_second

        attr_reader :target_write_ops_per_second

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @target_write_bytes_per_second = args['targetWriteBytesPerSecond']
          @target_read_bytes_per_second = args['targetReadBytesPerSecond']
          @target_read_ops_per_second = args['targetReadOpsPerSecond']
          @target_write_ops_per_second = args['targetWriteOpsPerSecond']
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionAutomaticScalingDiskUtilization"
        end
      end
    end
  end
end
