# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionAutomaticScalingRequestUtilization
        attr_reader :target_request_count_per_second

        attr_reader :target_concurrent_requests

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @target_request_count_per_second = args['targetRequestCountPerSecond']
          @target_concurrent_requests = args['targetConcurrentRequests']
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionAutomaticScalingRequestUtilization"
        end
      end
    end
  end
end
