# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionAutomaticScalingCpuUtilization
        attr_reader :target_utilization

        attr_reader :aggregation_window_length

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @target_utilization = args['targetUtilization']
          @aggregation_window_length = args['aggregationWindowLength']
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionAutomaticScalingCpuUtilization"
        end
      end
    end
  end
end
