# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/accesscontextmanager/property/serviceperimeter_spec_egress_policies_egress_to_operations_method_selectors'
module GoogleInSpec
  module AccessContextManager
    module Property
      class ServicePerimeterSpecEgressPoliciesEgressToOperations
        attr_reader :service_name

        attr_reader :method_selectors

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @service_name = args['serviceName']
          @method_selectors = GoogleInSpec::AccessContextManager::Property::ServicePerimeterSpecEgressPoliciesEgressToOperationsMethodSelectorsArray.parse(args['methodSelectors'], to_s)
        end

        def to_s
          "#{@parent_identifier} ServicePerimeterSpecEgressPoliciesEgressToOperations"
        end
      end

      class ServicePerimeterSpecEgressPoliciesEgressToOperationsArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return ServicePerimeterSpecEgressPoliciesEgressToOperations.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| ServicePerimeterSpecEgressPoliciesEgressToOperations.new(v, parent_identifier) }
        end
      end
    end
  end
end
