# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/accesscontextmanager/property/serviceperimeter_status_ingress_policies_ingress_to_operations'
module GoogleInSpec
  module AccessContextManager
    module Property
      class ServicePerimeterStatusIngressPoliciesIngressTo
        attr_reader :resources

        attr_reader :operations

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @resources = args['resources']
          @operations = GoogleInSpec::AccessContextManager::Property::ServicePerimeterStatusIngressPoliciesIngressToOperationsArray.parse(args['operations'], to_s)
        end

        def to_s
          "#{@parent_identifier} ServicePerimeterStatusIngressPoliciesIngressTo"
        end
      end
    end
  end
end
